version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: marketinsight
      POSTGRES_PASSWORD: marketinsightpassword
      POSTGRES_DB: marketinsightdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: